### ISSUE TITLE
Error when trying to test or run

### ISSUE THREAD

**Issue by pedrotnascimento** [guilhermechapiewski/titanium-jasmine#5]
Hey man,
I followed the tutorial and I'm getting this error:
[INFO] Performing clean build
[ERROR] clang: error: invalid deployment target for -stdlib=libc++ (requires iOS 5.0 or later)
[ERROR] 
[ERROR] Error: Traceback (most recent call last):
  File "/Users/tcapplab/Library/Application Support/Titanium/mobilesdk/osx/5.5.0.GA/iphone/builder.py", line 1379, in main
    execute_xcode("iphonesimulator%s" % link_version,["GCC_PREPROCESSOR_DEFINITIONS=**LOG__ID**=%s DEPLOYTYPE=development TI_DEVELOPMENT=1 DEBUG=1 TI_VERSION=%s %s %s" % (log_id,sdk_version,debugstr,kroll_coverage)],False)
  File "/Users/tcapplab/Library/Application Support/Titanium/mobilesdk/osx/5.5.0.GA/iphone/builder.py", line 1286, in execute_xcode
    output = run.run(args,False,False,o)
  File "/Users/tcapplab/Library/Application Support/Titanium/mobilesdk/osx/5.5.0.GA/iphone/run.py", line 41, in run
    sys.exit(rc)
SystemExit: 65

Do you have any idea how can I solve this? I did a deep search on internet but without any success.
It happens in test or run mode.
I tested in Mac.
Thanks

**Comment by 779nhan** [comment]
Code
